# Завдання
Ймовірність того, що при перевірці деталь деталь виявиться стандартною, дорівнює 0,6. Перевірці підлягають 3 деталі. Побудувати закон розподілу системи двох дискретних випадкових величин $X -$ появи числа бракованих деталей, і $Y -$ появи числа стандартних деталей. 
Обчислити коефіцієнт кореляції $r_{xy}$

# Розв'язок

Запишемо закон у табличній формі:

| Y\X  | 0      |  1      | 2         | 3          | $Py_i$  |
|---   |---     |---      |---        |---         |---      |
| 0    |  0     |  0      |  0        |  P(x4,y1)  |         |
| 1    |  0     |  0      |  P(x3,y2) |  0         |         |
| 2    |  0     | P(x2,y3)|  0        |  0         |         |
| 3    |P(x1,y4)|  0      |  0        |  0         |         |
| 𝑃𝑥𝑖   |        |         |           |            |         |

де

$P(x_1,y_4) = C^3_3p^3q^0$;

$P(x_2,y_3) = C^2_3p^2q^1$;

$P(x_3,y_2) = C^1_3p^1q^2$;

$P(x_1,y_4) = C^0_3p^0q^3$,

де $p = 0,6$; а $q = 1-0,6=0,4$.

$P(x_1,y_4) = C^3_3p^3q^0 = \frac{3!}{3!⋅(3-3)!}⋅0,6^3⋅0,4^0=$

In [2]:
round(0.6**3,3)

0.216

$P(x_2,y_3) = C^2_3p^2q^1 = \frac{3!}{2!⋅(3-2)!}⋅0,6^2⋅0,4^1=$

In [7]:
round(3*0.6**2*0.4,3)

0.432

$P(x_3,y_2) = C^1_3p^1q^2 = \frac{3!}{1!⋅(3-1)!}⋅0,6^1⋅0,4^2=$

In [6]:
round(3*0.6*0.4**2,3)

0.288

$P(x_1,y_4) = C^0_3p^0q^3 = \frac{3!}{0!⋅(3-0)!}⋅0,6^0⋅0,4^3=$

In [9]:
round(0.4**3,3)

0.064

Підставимо значення у таблицю:

| Y\X  | 0      |  1      | 2         | 3          | $Py_i$  |
|---   |---     |---      |---        |---         |---      |
| 0    |  0     |  0      |  0        |  0.064     |  0.064  |
| 1    |  0     |  0      |  0.288    |  0         | 0.288   |
| 2    |  0     | 0.432   |  0        |  0         |0.432    |
| 3    |  0.216 |  0      |  0        |  0         |   0.216 |
| 𝑃𝑥𝑖   | 0.216  |   0.432 |  0.288    |  0.064     |    1     |

1) Розрахуємо умовні математичні очікування.

$M(Y/x) = \sum^m_{j=1}y_jp(y_j,x)$

$M(X/y) = \sum^n_{i=1}x_ip(x_i,y)$

$M(X/y) = 0∙0,216 + 1∙0,432 + 2∙0,288 + 3∙0,064 =$

In [11]:
round(0*0.216 + 1*0.432 + 2*0.288 + 3*0.064, 3)

1.2

$M(Y/x) = 0∙0,064 + 1∙0,288 + 2∙0,432 + 3∙0,216 =$

In [12]:
round(0*0.064 + 1*0.288 + 2*0.432 + 3*0.216, 3)

1.8

2) Для середньоквадратичного відхилення спочатку визначимо умовну дисперсію:
$D[Y/X=x] = M[(Y-M[Y])^2] = 0,064∙(0-1,8)^2+0,288∙(1-1,8)^2+0,432∙(2-1,8)^2+0,216∙(3-1,8)^2=$

In [14]:
round(0.064*(0-1.8)**2+0.28*(1-1.8)**2+0.432*(2-1.8)**2+0.216*(3-1.8)**2, 3)

0.715

$D[X/Y=y] = M[(X-M[X])^2] =0,216∙(0-1,2)^2+0,432∙(1-1,2)^2+0,288∙(2-1,2)^2+0,064∙(3-1,2)^2=$

In [15]:
round(0.216*(0-1.2)**2+0.432*(1-1.2)**2+0.288*(2-1.2)**2+0.064*(3-1.2)**2, 3)

0.72

Середньоквадратичне відхилення відповідно:
1) $\sigma_y = \sqrt{D[Y/X=x]} = \sqrt{0.715} = $

In [16]:
round(0.715**0.5, 3)

0.846

2) $\sigma_x = \sqrt{D[X/Y=y]} = \sqrt{0.72} =$

In [17]:
round(0.72**0.5, 3)

0.849

3. Розрахуємо коефіцієнти коваріації та кореляції.

$cov(X,Y) = M[XY] - M[X]M[Y] = $

In [21]:
round((1*2*0.288 + 1*2*0.432) - 1.8*1.2, 3)

-0.72

Коефіцієнт кореляції відповідно:
$r_{xy} = \frac{cov(X,Y)}{\sigma_x ∙ \sigma_y} = \frac{-0.72}{0.846∙0.849} = $.


In [24]:
round(-0.72/(0.846*0.849), 2)

-1.0